---
- hosts: host03
  become: yes

  tasks:
    - name: "Install packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql-{{ postgresql_version }}
        - postgresql-contrib-{{ postgresql_version }}
        - python3-pexpect

    - name: Настройка listen addresses
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = 'localhost, {{ db_repl_host }}'"
        state: present     

    - name: Stop PostgreSQL
      service:
        name: postgresql
        state: stopped     

    - name: Удаление предыдущих данных PostgreSQL
      file:
        path: "/var/lib/postgresql/{{ postgresql_version }}/main/"
        state: absent
      become: yes
      become_user: postgres    

    - name: Создание репликации базы данных
      command: "pg_basebackup -R -h {{ db_master_host }} -U {{ db_repl_user }} -D /var/lib/postgresql/{{ postgresql_version }}/main -P"
      become: yes
      become_user: postgres      
      register: result
      until: result is not failed
      retries: 3
      delay: 5
      environment:
        PGUSER: "{{ db_repl_user }}"
        PGPASSWORD: "{{ db_repl_password }}" 

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started

