---
- hosts: host02
  become: yes

  tasks:

  - name: "Install Python"
    apt: "name={{ item }} state=present"
    with_items:
      - python3
      - python3-pip
      - python3-venv

  - name: "Clone git repo"
    git:
      repo: "{{bot_repo}}"
      dest: ~/{{item.repo_dir}}
      clone: yes
      update: yes
    with_items:
      - {repo_dir: devops_bot}    

  - name: "Environment variables for bot"
    copy:
       src: .env
       dest: "~/{{item.repo_dir}}"
    become: yes   
    with_items:
       - {repo_dir: devops_bot}        

  - name: "Install dependencies" 
    shell: python3 -m venv ~/myenv && source ~/myenv/bin/activate && pip install --no-cache-dir -r ~/{{item.repo_dir}}/requirements.txt 
    become: yes
    args:
     executable: /bin/bash
    with_items:
      - {repo_dir: devops_bot}     

  - name: "Run bot" 
    shell: source ~/myenv/bin/activate && python3 ~/{{item.repo_dir}}/bot.py 
    become: yes
    args:
       executable: /bin/bash
    with_items:
     - {repo_dir: devops_bot}     


